CREATE TABLE [dbo].[PR_tbl_ProjectStaff] (
    [PSTID]              INT           IDENTITY (1, 1) NOT NULL,
    [SNo]                INT           NOT NULL,
    [OID]                INT           NULL,
    [ETID]               INT           NULL,
    [ECID]               INT           NULL,
    [EGID]               INT           NULL,
    [EmpGroup]           VARCHAR (MAX) NULL,
    [PSID]               INT           NULL,
    [PayScale]           VARCHAR (MAX) NULL,
    [DID]                INT           NULL,
    [DeptID]             VARCHAR (MAX) NULL,
    [DSID]               INT           NULL,
    [Design]             VARCHAR (MAX) NULL,
    [AttendanceID]       DECIMAL (18)  NULL,
    [EmpID]              DECIMAL (18)  NULL,
    [Name]               VARCHAR (MAX) NULL,
    [Password]           VARCHAR (MAX) NULL,
    [Email]              VARCHAR (MAX) NULL,
    [Mobile]             DECIMAL (10)  NULL,
    [Aadhar]             VARCHAR (50)  NULL,
    [DOJ]                DATETIME      NULL,
    [DOR]                DATETIME      NULL,
    [Gender]             VARCHAR (50)  NULL,
    [PAN]                VARCHAR (50)  NULL,
    [BankAcType]         VARCHAR (MAX) NULL,
    [BankName]           VARCHAR (MAX) NULL,
    [BankBranch]         VARCHAR (MAX) NULL,
    [BankAccNo]          VARCHAR (50)  NULL,
    [IFSCCode]           VARCHAR (MAX) NULL,
    [Photo]              VARCHAR (MAX) NULL,
    [PTID]               INT           NULL,
    [ProjectCode]        VARCHAR (MAX) NULL,
    [ProjectTitle]       VARCHAR (MAX) NULL,
    [ProjectCoordinator] VARCHAR (MAX) NULL,
    [HEmpID]             INT           NULL,
    [CentreHead]         VARCHAR (MAX) NULL,
    [DOB]                DATETIME      NULL,
    [StartDate]          DATETIME      NULL,
    [EndDate]            DATETIME      NULL,
    [BasicPay]           DECIMAL (18)  NULL,
    [GrossSal]           DECIMAL (18)  NULL,
    [QuarterAllotted]    VARCHAR (MAX) NULL,
    [QuarterType]        VARCHAR (MAX) NULL,
    [QuarterNo]          VARCHAR (MAX) NULL,
    [OfficeOrderNo]      VARCHAR (MAX) NULL,
    [OfficeOrderDate]    DATETIME      NULL,
    [OOIssuingAuthority] VARCHAR (MAX) NULL,
    [Role]               INT           NULL,
    [Status]             VARCHAR (50)  NULL,
    [UID]                INT           NULL,
    [UName]              VARCHAR (MAX) NULL,
    [Dated]              DATETIME      NULL,
    [FDOJ]               DATETIME      NULL,
    [EDate]              DATETIME      NULL,
    [CitizenType]        VARCHAR (MAX) NULL,
    [AppointmentOrder]   VARCHAR (MAX) NULL,
    [ISHOC]              VARCHAR (50)  NULL,
    [OTP]                VARCHAR (50)  NULL,
    [Block]              VARCHAR (50)  NULL,
    [Floor]              VARCHAR (50)  NULL,
    [Intercom]           VARCHAR (50)  NULL,
    [RoomNo]             VARCHAR (50)  NULL,
    [Flag1]              INT           NULL,
    [Flag2]              INT           NULL,
    [IsIncharge]         VARCHAR (50)  NULL,
    [bIsSrvHstrFilled]   BIT           DEFAULT ((0)) NULL,
    CONSTRAINT [PK_PR_tbl_ProjectStaff] PRIMARY KEY CLUSTERED ([PSTID] ASC)
);

