CREATE TABLE [dbo].[PR_tbl_Employee] (
    [EID]         INT           IDENTITY (1, 1) NOT NULL,
    [OID]         INT           NULL,
    [ETID]        INT           NULL,
    [EmpType]     VARCHAR (MAX) NULL,
    [ECID]        INT           NULL,
    [EmpCategory] VARCHAR (MAX) NULL,
    [EGID]        INT           NULL,
    [EmpGroup]    VARCHAR (MAX) NULL,
    [DID]         INT           NULL,
    [DeptID]      VARCHAR (MAX) NULL,
    [DSID]        INT           NULL,
    [Design]      VARCHAR (MAX) NULL,
    [EmpID]       INT           NOT NULL,
    [Name]        VARCHAR (MAX) NULL,
    [FathersName] VARCHAR (MAX) NULL,
    [Email]       VARCHAR (MAX) NULL,
    [Password]    VARCHAR (MAX) NULL,
    [Mobile]      DECIMAL (10)  NULL,
    [Aadhar]      VARCHAR (50)  NULL,
    [DOB]         DATETIME      NULL,
    [DOJ]         DATETIME      NULL,
    [Gender]      VARCHAR (50)  NULL,
    [PAN]         VARCHAR (50)  NOT NULL,
    [BankAcType]  VARCHAR (MAX) NULL,
    [BankName]    VARCHAR (MAX) NULL,
    [BankBranch]  VARCHAR (MAX) NULL,
    [BankAccNo]   DECIMAL (18)  NOT NULL,
    [IFSCCode]    VARCHAR (MAX) NULL,
    [Address]     VARCHAR (MAX) NULL,
    [State]       VARCHAR (MAX) NULL,
    [Photo]       VARCHAR (MAX) NULL,
    [Role]        INT           NULL,
    [Status]      VARCHAR (50)  NULL,
    [UID]         INT           NULL,
    [UName]       VARCHAR (MAX) NULL,
    [Dated]       DATETIME      NULL,
    [ISHOC]       VARCHAR (50)  NULL,
    [OTP]         VARCHAR (50)  NULL,
    [Block]       VARCHAR (MAX) NULL,
    [Floor]       VARCHAR (MAX) NULL,
    [Intercom]    VARCHAR (MAX) NULL,
    [RoomNo]      VARCHAR (MAX) NULL,
    CONSTRAINT [PK_PR_tbl_Employee] PRIMARY KEY CLUSTERED ([EID] ASC)
);

